### PR TITLE
bump up hackney version to support OTP 23

### LINKED ISSUE #15: Update hackney to support OTP 23
**Describe the bug**
{:error,
 {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}}}

### PR DESCRIPTION
**Pull request by lenileiro**
## What is the Purpose?

resolve #15

## What was the approach?

Briefly describe the approach used to address the issue

## Are there any concerns to addressed further before or after merging this PR?

State some additional info if any. For instance running `mix deps.get` or setting some environment variable(s)

## Mentions?

Mention persons you'd like to review this PR

## Issue(s) affected?

List of issues addressed by this PR.

### CODE REVIEW

**Comment by manuelgeek** [comment]
looks good, the failing pipeline is not associated to the project
The error comes because you're not a user of the repo
I did a fix, try pull from upstream develop and try again

**Review by manuelgeek — COMMENTED** [review]
@lenileiro  I left a comment there

**Comment by lenileiro** [comment]
It should be good to go.

**Review by manuelgeek — APPROVED** [review]
looks good

**Pull request merged**
