### PR TITLE
Feature/transaction status

### PR DESCRIPTION
**Pull request by kamalogudah**
## What is the Purpose?

Briefly describe what the PR addresses

## What was the approach?

Briefly describe the approach used to address the issue

## Are there any concerns to addressed further before or after merging this PR?

State some additional info if any. For instance running `mix deps.get` or setting some environment variable(s)

## Mentions?

Mention persons you'd like to review this PR

## Issue(s) affected?

List of issues addressed by this PR.

### CODE REVIEW

**Comment by manuelgeek** [comment]
@kamalogudah kindly rebase, this solves the pipeline issues so that i can review
you have a PR to this branch from @lenileiro  too

**Comment by manuelgeek** [comment]
@kamalogudah  check on the conflicts

**Comment by kamalogudah** [comment]
> @kamalogudah check on the conflicts

You can check now.

**Comment by kamalogudah** [comment]
oops some conflicts let me address them.

**Review by lenileiro — APPROVED** [review]
LGTM

**Comment by lenileiro** [comment]
@manuelgeek @kamalogudah this is ready to ship

**Pull request merged**
