### PR TITLE
the reversal

### PR DESCRIPTION
**Pull request by okothkongo**
## What is the Purpose?

Briefly describe what the PR addresses

## What was the approach?

Briefly describe the approach used to address the issue

## Are there any concerns to addressed further before or after merging this PR?

State some additional info if any. For instance running `mix deps.get` or setting some environment variable(s)

## Mentions?

Mention persons you'd like to review this PR

## Issue(s) affected?

List of issues addressed by this PR.

### CODE REVIEW

**Comment by manuelgeek** [comment]
@okothkongo @MidigoF kindly check on the test coverages, you might need to use `mix coveralls.html` then check on `/cover/excoveralls.html`
Then work on the module document, follow the others like in `b2b.ex` or `account_balance.ex`
with the example

**Comment by manuelgeek** [comment]
also add test cases for the other API options, this will increase the coverage

**Comment by lenileiro** [comment]
@okothkongo @MidigoF I have made a pull request against your PR that improves the test coverage to 97.8% with 100% coverage to the reversal module.

**Comment by manuelgeek** [comment]
@okothkongo @MidigoF @lenileiro awesome. looks good

**Review by manuelgeek — APPROVED** [review]

**Pull request merged**
