### PR TITLE
enable account info inquiry

### LINKED ISSUE #64: Feature Request: Account Inquiry - Bank Accounts
**Is your feature request related to a problem? Please describe.**
Get account details [Account Inquiry - Bank Accounts](https://developer.jengaapi.io/reference#account-inquiry)

### PR DESCRIPTION
**Pull request by r-coh**
## What is the Purpose?
Enables requesting of Bank Account information.

## Issue(s) affected?
Fixes #64

### CODE REVIEW

**Comment by manuelgeek** [comment]
@r-coh  any updates on the fixes you need to do?

**Comment by r-coh** [comment]
@manuelgeek this one should have worked, am not sure what happened with CI

**Review by manuelgeek — APPROVED** [review]
looks good

**Comment by manuelgeek** [comment]
@r-coh  the issue was with the pipeline, i update and pushed

**Pull request merged**
